version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=Product
    depends_on:
      - mongo

  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=Customer
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=Order
    depends_on:
      - mongo

volumes:
  mongo-data:

